# Core concepts are direct evidence of the bolted-joint/onsite-machining/
# pipeline-integrity work Tritorc's tools are actually used for. Context
# concepts only identify an industry sector -- necessary but not sufficient,
# since any company adjacent to oil & gas/power/steel can mention them
# without ever doing bolting, tensioning, or machining work. Verified live
# that context-only concepts (oil_gas + refinery + industrial_maintenance +
# power_plant + a role phrase) can otherwise sum to score=100/tier=best with
# zero real evidence of Tritorc-relevant work -- see CORE_CONCEPTS gating in
# _tier_from_score_and_role().
CORE_CONCEPTS = {
    "controlled_bolting", "bolt_tensioning", "flange_management", "flange_facing",
    "onsite_machining", "hot_tapping", "pipeline_integrity", "pipeline_maintenance",
    "hydrotesting", "leak_sealing", "heat_exchanger", "retubing", "structural_bolting",
    "joint_integrity", "torque_services", "hot_bolting", "line_stopping",
}

CONCEPT_WEIGHTS = {
    "controlled_bolting": 20,
    "bolt_tensioning": 18,
    "flange_management": 16,
    "flange_facing": 18,
    "onsite_machining": 18,
    "hot_tapping": 18,
    "pipeline_integrity": 20,
    "pipeline_maintenance": 16,
    "hydrotesting": 16,
    "leak_sealing": 16,
    "heat_exchanger": 16,
    "retubing": 16,
    "shutdown_turnaround": 18,
    "oil_gas": 14,
    "refinery": 16,
    "petrochemical": 16,
    "fertilizer_plant": 14,
    "grain_elevator": 14,
    "power_plant": 14,
    "steel_plant": 14,
    "wind_turbine": 14,
    "epc": 12,
    "industrial_maintenance": 12,
    "pressure_vessel": 14,
    "structural_bolting": 18,
    "joint_integrity": 20,
    "torque_services": 16,
    "hot_bolting": 18,
    "line_stopping": 16,
    "lng": 14,
    "shipyard": 14,
    "mining": 12,
    "cement_plant": 14,
    "nuclear": 14,
    "fpso": 14,
}

NEGATIVE_CONCEPT_WEIGHTS = {
    "roofing": 28,
    "remodeling": 28,
    "hvac": 28,
    "plumbing": 30,
    "school": 28,
    "chamber_of_commerce": 35,
    "real_estate": 30,
    "restaurant": 35,
    "retail": 24,
    "hardware_store": 30,
    "residential_construction": 24,
    "hotel": 28,
    "clinic": 28,
    "tool_distributor": 18,
    "fastener_supplier": 18,
    "equipment_dealer": 16,
}

CONCEPT_PHRASES = {
    "en": {
        "controlled_bolting": ["controlled bolting"],
        "bolt_tensioning": ["bolt tensioning", "bolt tensioner"],
        "flange_management": ["flange management"],
        "flange_facing": ["flange facing"],
        "onsite_machining": ["onsite machining", "on-site machining"],
        "hot_tapping": ["hot tapping", "hot tap"],
        "pipeline_integrity": ["pipeline integrity"],
        "pipeline_maintenance": ["pipeline maintenance"],
        "hydrotesting": ["hydrostatic testing", "hydrotesting"],
        "leak_sealing": ["leak sealing", "online leak sealing"],
        "heat_exchanger": ["heat exchanger"],
        "retubing": ["retubing", "re-tubing"],
        # Bare "shutdown"/"turnaround" matched unrelated uses (e.g. "emergency
        # shutdown valve", "turnaround time") -- these compound phrases are
        # specific to a plant maintenance event.
        "shutdown_turnaround": ["plant shutdown", "shutdown maintenance", "turnaround maintenance", "shutdown services", "plant turnaround"],
        "oil_gas": ["oil and gas", "oil & gas"],
        "refinery": ["refinery", "refineries"],
        "petrochemical": ["petrochemical"],
        "fertilizer_plant": ["fertilizer plant", "fertilizer terminal", "fertilizer production"],
        "grain_elevator": ["grain elevator", "grain terminal", "agri-processing plant", "agricultural processing plant"],
        "power_plant": ["power plant"],
        "steel_plant": ["steel plant", "steel mill"],
        "wind_turbine": ["wind turbine"],
        # The bare 3-letter acronym "epc" is a substring match (see
        # _find_concepts) and was confirmed to match inside unrelated
        # Spanish/Portuguese words like "recepción"/"recepção" (reception).
        # Specific multi-word phrases avoid that false-positive class.
        "epc": ["epc contractor", "epc project", "epc services", "engineering, procurement and construction"],
        "industrial_maintenance": ["industrial maintenance"],
        "pressure_vessel": ["pressure vessel"],
        "structural_bolting": ["structural bolting", "high strength bolting", "high-strength bolts", "structural steel erection", "friction grip bolting", "bridge construction"],
        "joint_integrity": ["joint integrity", "flange joint integrity", "bolted joint"],
        "torque_services": ["torque wrench", "torquing services", "bolting services"],
        "hot_bolting": ["hot bolting"],
        "line_stopping": ["line stopping", "line stop"],
        "lng": ["lng terminal", "liquefied natural gas"],
        "shipyard": ["shipyard", "ship repair"],
        "mining": ["mining", "mineral processing"],
        "cement_plant": ["cement plant"],
        "nuclear": ["nuclear power plant", "nuclear outage"],
        "fpso": ["fpso", "offshore platform"],
    },
    "es": {
        "shutdown_turnaround": ["parada de planta", "mantenimiento de parada"],
        "industrial_maintenance": ["mantenimiento industrial", "mantenimiento de plantas"],
        "onsite_machining": ["mecanizado in situ", "mecanizado en sitio"],
        "pipeline_integrity": ["integridad de ductos", "integridad de tuberías"],
        "pipeline_maintenance": ["mantenimiento de ductos", "mantenimiento de tuberías"],
        "hydrotesting": ["prueba hidrostática", "ensayo hidrostático"],
        "hot_tapping": ["hot tapping", "taponamiento en caliente"],
        "flange_management": ["bridas", "gestión de bridas"],
        "controlled_bolting": ["apriete controlado", "atornillado controlado"],
        "heat_exchanger": ["intercambiador de calor"],
        "oil_gas": ["petróleo y gas", "oil and gas"],
        "refinery": ["refinería", "refinerias"],
        "petrochemical": ["petroquímica"],
        "power_plant": ["central eléctrica"],
        "steel_plant": ["planta siderúrgica", "acería"],
        "epc": ["contratista epc", "proyecto epc", "epc contractor"],
    },
    "fr": {
        "shutdown_turnaround": ["arrêt technique", "arrêt de maintenance"],
        "industrial_maintenance": ["maintenance industrielle"],
        "onsite_machining": ["usinage sur site"],
        "pipeline_integrity": ["intégrité des pipelines", "intégrité des canalisations"],
        "pipeline_maintenance": ["maintenance des pipelines"],
        "hydrotesting": ["essai hydrostatique", "test hydrostatique"],
        "hot_tapping": ["piquage en charge", "hot tapping"],
        "flange_management": ["bride", "gestion des brides"],
        "controlled_bolting": ["serrage contrôlé"],
        "heat_exchanger": ["échangeur de chaleur"],
        "oil_gas": ["pétrole et gaz", "oil and gas"],
        "refinery": ["raffinerie"],
        "petrochemical": ["pétrochimie", "pétrochimique"],
        "power_plant": ["centrale électrique"],
        "steel_plant": ["aciérie"],
        "epc": ["contractant epc", "projet epc", "epc contractor"],
    },
    "pt": {
        "shutdown_turnaround": ["parada de manutenção", "parada de planta"],
        "industrial_maintenance": ["manutenção industrial"],
        "onsite_machining": ["usinagem em campo", "usinagem no local"],
        "pipeline_integrity": ["integridade de dutos", "integridade de tubulações"],
        "pipeline_maintenance": ["manutenção de dutos", "manutenção de tubulações"],
        "hydrotesting": ["teste hidrostático", "ensaio hidrostático"],
        "hot_tapping": ["hot tapping"],
        "flange_management": ["flange", "gestão de flanges"],
        "controlled_bolting": ["aperto controlado"],
        "heat_exchanger": ["trocador de calor", "permutador de calor"],
        "oil_gas": ["óleo e gás", "petróleo e gás", "oil and gas"],
        "refinery": ["refinaria"],
        "petrochemical": ["petroquímica"],
        "power_plant": ["usina elétrica"],
        "steel_plant": ["siderúrgica"],
        "epc": ["contratante epc", "projeto epc", "epc contractor"],
    },
    "de": {
        "shutdown_turnaround": ["anlagenstillstand", "wartungsstillstand"],
        "industrial_maintenance": ["industrielle instandhaltung", "industrie wartung"],
        "onsite_machining": ["vor-ort-bearbeitung", "bearbeitung vor ort"],
        "pipeline_integrity": ["pipeline-integrität", "integrität von pipelines"],
        "hydrotesting": ["hydrostatische prüfung"],
        "hot_tapping": ["anbohren unter druck", "hot tapping"],
        "flange_management": ["flansch", "flanschmanagement"],
        "controlled_bolting": ["kontrolliertes verschrauben"],
        "heat_exchanger": ["wärmetauscher"],
        "oil_gas": ["öl und gas"],
        "refinery": ["raffinerie"],
        "petrochemical": ["petrochemie"],
        "power_plant": ["kraftwerk"],
        "steel_plant": ["stahlwerk"],
        "epc": ["epc-auftragnehmer", "epc-projekt", "epc contractor"],
    },
}

NEGATIVE_CONCEPT_PHRASES = {
    "en": {
        "roofing": ["roofing"],
        "remodeling": ["remodeling", "renovation"],
        "hvac": ["hvac", "air conditioning"],
        "plumbing": ["plumbing"],
        "school": ["school district", "school"],
        "chamber_of_commerce": ["chamber of commerce"],
        "real_estate": ["real estate"],
        "restaurant": ["restaurant"],
        "retail": ["retail"],
        "hardware_store": ["hardware store"],
        "residential_construction": ["residential", "home builder", "apartment", "stucco", "landscaping"],
        "hotel": ["hotel"],
        "clinic": ["clinic"],
        "tool_distributor": ["tool distributor", "tools distributor", "industrial distributor", "authorized distributor", "hydraulic tool supplier", "wrench supplier", "stockist"],
        "fastener_supplier": ["fastener supplier", "bolt supplier"],
        "equipment_dealer": ["equipment dealer"],
    },
    "es": {
        "remodeling": ["reformas", "renovación"],
        "hvac": ["climatización", "aire acondicionado"],
        "plumbing": ["fontanería"],
        "school": ["colegio", "escuela"],
        "real_estate": ["inmobiliaria"],
        "residential_construction": ["residencial", "viviendas"],
    },
    "fr": {
        "plumbing": ["plomberie"],
        "real_estate": ["immobilier"],
        "residential_construction": ["résidentiel"],
        "restaurant": ["restauration"],
    },
    "pt": {
        "plumbing": ["encanamento"],
        "real_estate": ["imobiliário"],
        "residential_construction": ["residencial"],
    },
}

BUSINESS_ROLE_WEIGHTS = {
    "end_user_operator": 45,
    "industrial_service_contractor": 42,
    "epc_contractor": 34,
    "supplier_distributor": -45,
    "competitor_manufacturer": -60,
    "generic_local_service": -45,
}

BUSINESS_ROLE_PHRASES = {
    "en": {
        "end_user_operator": [
            "refinery operator",
            "pipeline operator",
            "plant operator",
            "terminal operator",
            "petrochemical plant",
            "fertilizer plant",
            "grain elevator",
            "grain terminal",
            "power plant",
            "steel mill",
            "wind farm",
            "production facility",
            "manufacturing facility",
        ],
        "industrial_service_contractor": [
            "shutdown contractor",
            "turnaround contractor",
            "maintenance contractor",
            "industrial maintenance services",
            "pipeline integrity services",
            "hydrostatic testing services",
            "hot tapping services",
            "leak sealing services",
            "onsite machining services",
            "field machining services",
            "plant maintenance",
        ],
        "epc_contractor": [
            "epc contractor",
            "engineering procurement construction",
            "industrial construction",
            "process plant construction",
            "oil and gas construction",
            "structural steel erection",
            "bridge construction",
            "heavy civil construction",
        ],
        # Bare "supplier"/"distributor"/"catalog"/"product range"/"sales of"
        # were removed: these are common in any B2B site's language and don't
        # specifically indicate reselling Tritorc-category tools -- kept only
        # the tool-specific phrasing below.
        "supplier_distributor": [
            "authorized distributor",
            "reseller",
            "stockist",
            "rental tools",
            "tool rental",
            "valve supplier",
            "fitting supplier",
            "hose supplier",
            "hydraulic supplier",
            "industrial supplies",
            "machine tools",
            "cnc machines",
        ],
        "competitor_manufacturer": [
            "hydraulic torque wrench manufacturer",
            "torque wrench supplier",
            "bolt tensioner supplier",
            "bolt tensioner manufacturer",
            "flange facing machine",
            "pipe cutting machine",
            "pipe beveling machine",
            "tube expander manufacturer",
            "hydraulic tools manufacturer",
            "controlled bolting tools",
            "torque tools",
            "hytorc",
            "enerpac",
            "rad torque",
            "hi-force",
            "atlas copco",
        ],
        "generic_local_service": [
            "building maintenance",
            "facility management",
            "residential construction",
            "home renovation",
            "bathroom",
            "air conditioning",
            "plumbing",
            "roofing",
            "landscaping",
        ],
    },
    "es": {
        "end_user_operator": [
            "operador de refinería",
            "operador de ductos",
            "operador de planta",
            "planta petroquímica",
            "planta de fertilizantes",
            "central eléctrica",
            "acería",
            "parque eólico",
            "instalación industrial",
        ],
        "industrial_service_contractor": [
            "contratista mantenimiento",
            "contratista de mantenimiento",
            "mantenimiento industrial",
            "parada de planta",
            "servicios de parada",
            "integridad de ductos",
            "mantenimiento de ductos",
            "prueba hidrostática",
            "ensayo hidrostático",
            "hot tapping",
            "mecanizado en sitio",
            "mecanizado in situ",
            "servicios petroleros",
        ],
        "epc_contractor": [
            "contratista epc",
            "epc industrial",
            "ingeniería procura construcción",
            "construcción industrial",
            "obras industriales",
        ],
        # Bare "distribuidor"/"representante"/"venta de"/"catálogo"/"stock" and
        # bare "válvulas"/"fittings"/"mangueras" removed -- same false-positive
        # risk as the English list's bare "supplier"/"distributor"; kept only
        # tool-specific compound phrasing.
        "supplier_distributor": [
            "distribuidor autorizado",
            "proveedor de válvulas",
            "proveedor de mangueras",
            "herramientas hidráulicas",
            "máquinas herramientas",
            "máquinas cnc",
        ],
        "competitor_manufacturer": [
            "llave de torque hidráulica",
            "llaves de torque",
            "tensionadores de pernos",
            "herramientas de torque",
            "herramientas hidráulicas",
            "máquina refrentadora de bridas",
            "cortadora de tubos",
            "biseladora de tubos",
            "expansor de tubos",
            "hytorc",
            "enerpac",
            "rad torque",
            "hi-force",
            "atlas copco",
        ],
        "generic_local_service": [
            "mantenimiento edilicio",
            "facility management",
            "construcción residencial",
            "reformas",
            "renovación",
            "bañeras",
            "aire acondicionado",
            "climatización",
            "fontanería",
        ],
    },
    "fr": {
        "industrial_service_contractor": ["maintenance industrielle", "arrêt technique", "usinage sur site", "essai hydrostatique"],
        "supplier_distributor": ["distributeur agréé", "fournisseur de vannes", "fournisseur de raccords", "outils hydrauliques"],
        "competitor_manufacturer": ["clé dynamométrique hydraulique", "tendeur de boulons", "outils hydrauliques", "hytorc", "enerpac"],
        "generic_local_service": ["maintenance bâtiment", "rénovation", "plomberie", "climatisation"],
    },
    "pt": {
        "industrial_service_contractor": ["manutenção industrial", "parada de manutenção", "integridade de dutos", "teste hidrostático"],
        "supplier_distributor": ["distribuidor autorizado", "fornecedor de válvulas", "fornecedor de mangueiras", "ferramentas hidráulicas"],
        "competitor_manufacturer": ["chave de torque hidráulica", "tensionador de parafusos", "ferramentas hidráulicas", "hytorc", "enerpac"],
        "generic_local_service": ["manutenção predial", "reforma", "encanamento", "ar condicionado"],
    },
    "de": {
        "industrial_service_contractor": ["industrielle instandhaltung", "anlagenstillstand", "pipeline-integrität", "hydrostatische prüfung"],
        "supplier_distributor": ["autorisierter händler", "ventilhändler", "hydraulikwerkzeuge"],
        "competitor_manufacturer": ["hydraulischer drehmomentschlüssel", "bolzenspanner", "hydraulikwerkzeuge", "hytorc", "enerpac"],
        "generic_local_service": ["gebäudewartung", "renovierung", "sanitär", "klimaanlage"],
    },
}

LOCALIZED_QUERY_TERMS = {
    "es": [
        "contratista mantenimiento refinería",
        "servicios integridad de ductos",
        "mecanizado in situ industrial",
        "contratista parada de planta",
        "mantenimiento planta petroquímica",
    ],
    "fr": [
        "maintenance industrielle raffinerie",
        "services intégrité pipeline",
        "usinage sur site industriel",
        "arrêt technique industriel",
        "maintenance pétrochimique",
    ],
    "pt": [
        "manutenção industrial refinaria",
        "serviços integridade de dutos",
        "usinagem em campo industrial",
        "parada de manutenção industrial",
        "manutenção petroquímica",
    ],
    "de": [
        "industrielle instandhaltung raffinerie",
        "pipeline-integrität dienstleister",
        "bearbeitung vor ort industrie",
        "anlagenstillstand wartung",
        "petrochemie wartung",
    ],
}
